// <auto-generated />
namespace CEvery.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class added_fields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_fields));
        
        string IMigrationMetadata.Id
        {
            get { return "201410051420346_added_fields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
