// <auto-generated />
namespace CEvery.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class added_fields3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_fields3));
        
        string IMigrationMetadata.Id
        {
            get { return "201410051509273_added_fields3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
