// <auto-generated />
namespace CEvery.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class addsubscriptionduplicate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addsubscriptionduplicate));
        
        string IMigrationMetadata.Id
        {
            get { return "201410100629019_add-subscriptionduplicate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
